runtime: nodejs16

instance_class: F1
automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms
  max_instances: 1

handlers:
  # Serve all static files with url ending with a file extension
  - url: /(.*\..+)$
    secure: always
    redirect_http_response_code: 301
    static_files: build/\1
    upload: build/(.*\..+)$
  # Catch all handler to index.html
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    static_files: build/index.html
    upload: build/index.html
