DROP TABLE IF EXISTS permissions CASCADE;
-- CREATE USERS
CREATE TABLE permissions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name VARCHAR(64) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_permissions PRIMARY KEY (id),
  CONSTRAINT uq_permissions_name UNIQUE (name)
);
