DROP TABLE IF EXISTS roles CASCADE;
-- CREATE USERS
CREATE TABLE roles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name VARCHAR(32) NOT NULL,
  created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT pk_roles PRIMARY KEY (id),
  CONSTRAINT uq_roles_name UNIQUE (name)
);
