runtime: nodejs20

service: default

instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms
  min_instances: 1
  max_instances: 1
# instance_class: B1
# basic_scaling:
#   max_instances: 1
#   idle_timeout: 10m

inbound_services:
  - warmup

includes:
  - env.yaml
  
handlers:
  - url: /.*
    secure: always
    redirect_http_response_code: 301
    script: auto
