runtime: nodejs16

service: api

instance_class: F1
automatic_scaling:
  min_idle_instances: 1
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms
  max_instances: 1
# instance_class: B1
# basic_scaling:
#   max_instances: 1
#   idle_timeout: 10m

includes:
  - env.yaml
  